using ExciseTaxAudit.API.Data;
using ExciseTaxAudit.API.Models;
using Microsoft.EntityFrameworkCore;
using System.Text;

namespace ExciseTaxAudit.API.Services;

/// <summary>
/// Service for generating IRS-compliant exports and reports.
/// Supports Form 8849 worksheets and audit documentation.
/// </summary>
public class ExportService
{
    private readonly AuditContext _context;
    private readonly AuditTrailService _auditTrail;
    private readonly ILogger<ExportService> _logger;

    public ExportService(
        AuditContext context,
        AuditTrailService auditTrail,
        ILogger<ExportService> logger)
    {
        _context = context;
        _auditTrail = auditTrail;
        _logger = logger;
    }

    /// <summary>
    /// Generate IRS Form 8849 worksheet as CSV.
    /// </summary>
    public async Task<string> GenerateForm8849WorksheetAsync(
        int engagementId,
        string taxPeriod,
        string userId,
        string userName)
    {
        var transactions = await _context.TransactionRecords
            .Where(t => t.EngagementId == engagementId && 
                       t.Status == "APPROVED" &&
                       t.ClaimAmount > 0)
            .OrderBy(t => t.ClaimSchedule)
            .ThenBy(t => t.TransactionDate)
            .ToListAsync();

        var sb = new StringBuilder();
        
        // Header with metadata
        sb.AppendLine("IRS Form 8849 Fuel Tax Credit Worksheet");
        sb.AppendLine($"Tax Period: {taxPeriod}");
        sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"Generated By: {userName}");
        sb.AppendLine();
        
        // Column headers
        sb.AppendLine("Schedule,Transaction ID,Date,Merchant,State,Fuel Type,Quantity (Gal),Price/Unit,Net Cost,Tax Paid,Expected Tax,Claim Amount,Notes");
        
        // Data rows grouped by schedule
        decimal totalClaim = 0;
        foreach (var transaction in transactions)
        {
            var schedule = transaction.ClaimSchedule ?? "Unassigned";
            var claimAmount = transaction.ClaimAmount ?? 0;
            totalClaim += claimAmount;
            
            sb.AppendLine($"{schedule}," +
                         $"{transaction.RecordID}," +
                         $"{transaction.TransactionDate:yyyy-MM-dd}," +
                         $"\"{transaction.MerchantName}\"," +
                         $"{transaction.MerchantState}," +
                         $"\"{transaction.FuelType}\"," +
                         $"{transaction.Quantity:F2}," +
                         $"{transaction.PricePerUnit:F4}," +
                         $"{transaction.NetCost:F2}," +
                         $"{transaction.TotalTaxAmount:F2}," +
                         $"{CalculateExpectedTax(transaction):F2}," +
                         $"{claimAmount:F2}," +
                         $"\"{transaction.AnomalyReason?.Replace("\"", "\"\"")}\"");
        }
        
        // Summary
        sb.AppendLine();
        sb.AppendLine($"Total Transactions,{transactions.Count}");
        sb.AppendLine($"Total Claim Amount,${totalClaim:F2}");
        sb.AppendLine();
        sb.AppendLine("METHODOLOGY DISCLOSURE:");
        sb.AppendLine("Claims are based on statistical analysis and machine learning anomaly detection.");
        sb.AppendLine("Transactions flagged for potential tax overpayment have been reviewed and approved.");
        sb.AppendLine("Expected tax calculated based on published state tax rates and safe harbor provisions.");
        
        // Log export
        await _auditTrail.LogActionAsync(new AuditLog
        {
            Action = "EXPORT",
            EntityType = "ENGAGEMENT",
            EntityId = engagementId.ToString(),
            EngagementId = engagementId,
            UserId = userId,
            UserName = userName,
            UserRole = "",
            Comments = $"Exported Form 8849 worksheet for {taxPeriod} with {transactions.Count} claims totaling ${totalClaim:F2}"
        });

        return sb.ToString();
    }

    /// <summary>
    /// Generate comprehensive audit report.
    /// </summary>
    public async Task<string> GenerateAuditReportAsync(
        int engagementId,
        string userId,
        string userName)
    {
        var engagement = await _context.Engagements
            .Include(e => e.Client)
            .FirstOrDefaultAsync(e => e.Id == engagementId);

        if (engagement == null)
            throw new KeyNotFoundException($"Engagement {engagementId} not found");

        var transactions = await _context.TransactionRecords
            .Where(t => t.EngagementId == engagementId)
            .ToListAsync();

        var flagged = transactions.Where(t => t.AnomalyScore > 0.5f).ToList();
        var approved = transactions.Where(t => t.Status == "APPROVED").ToList();
        var claimed = transactions.Where(t => t.Status == "CLAIMED").ToList();

        var sb = new StringBuilder();
        sb.AppendLine("EXCISE TAX ANALYTICS REPORT");
        sb.AppendLine("=".PadRight(80, '='));
        sb.AppendLine();
        sb.AppendLine($"Client: {engagement.Client.Name}");
        sb.AppendLine($"Engagement: {engagement.EngagementName}");
        sb.AppendLine($"Period: {engagement.FiscalYear}");
        sb.AppendLine($"Report Date: {DateTime.UtcNow:yyyy-MM-dd}");
        sb.AppendLine($"Generated By: {userName}");
        sb.AppendLine();
        sb.AppendLine("EXECUTIVE SUMMARY");
        sb.AppendLine("-".PadRight(80, '-'));
        sb.AppendLine($"Total Transactions Analyzed: {transactions.Count:N0}");
        sb.AppendLine($"Anomalies Detected: {flagged.Count:N0} ({(flagged.Count * 100.0 / transactions.Count):F1}%)");
        sb.AppendLine($"Claims Approved: {approved.Count:N0}");
        sb.AppendLine($"Claims Submitted: {claimed.Count:N0}");
        sb.AppendLine($"Total Potential Recovery: ${approved.Sum(t => t.ClaimAmount ?? 0):N2}");
        sb.AppendLine();
        sb.AppendLine("BREAKDOWN BY STATUS");
        sb.AppendLine("-".PadRight(80, '-'));
        
        var statusGroups = transactions
            .GroupBy(t => t.Status)
            .OrderByDescending(g => g.Count());
        
        foreach (var group in statusGroups)
        {
            sb.AppendLine($"{group.Key}: {group.Count():N0} transactions (${group.Sum(t => t.ClaimAmount ?? 0):N2})");
        }
        
        sb.AppendLine();
        sb.AppendLine("METHODOLOGY");
        sb.AppendLine("-".PadRight(80, '-'));
        sb.AppendLine("1. Statistical Analysis: Z-score based price anomaly detection");
        sb.AppendLine("2. Tax Validation: Comparison against published state tax rates");
        sb.AppendLine("3. Machine Learning: Confidence scoring for anomaly classification");
        sb.AppendLine("4. Safe Harbor: Application of IRS safe harbor provisions where applicable");
        sb.AppendLine();

        // Log export
        await _auditTrail.LogActionAsync(new AuditLog
        {
            Action = "EXPORT",
            EntityType = "ENGAGEMENT",
            EntityId = engagementId.ToString(),
            EngagementId = engagementId,
            UserId = userId,
            UserName = userName,
            UserRole = "",
            Comments = $"Generated audit report with {transactions.Count} transactions"
        });

        return sb.ToString();
    }

    /// <summary>
    /// Export transaction details as CSV.
    /// </summary>
    public async Task<string> ExportTransactionDetailsAsync(
        int engagementId,
        string status,
        string userId,
        string userName)
    {
        var transactions = await _context.TransactionRecords
            .Where(t => t.EngagementId == engagementId && t.Status == status)
            .OrderByDescending(t => t.AnomalyScore)
            .ToListAsync();

        var sb = new StringBuilder();
        sb.AppendLine("Record ID,Transaction #,Date,Merchant,State,Fuel Type,Quantity,Price/Unit,Net Cost,Tax,Anomaly Score,Confidence,Status,Claim Amount,Schedule,Reviewed By,Approved By,Notes");
        
        foreach (var t in transactions)
        {
            sb.AppendLine($"{t.RecordID}," +
                         $"{t.TransactionNumber}," +
                         $"{t.TransactionDate:yyyy-MM-dd}," +
                         $"\"{t.MerchantName}\"," +
                         $"{t.MerchantState}," +
                         $"\"{t.FuelType}\"," +
                         $"{t.Quantity:F2}," +
                         $"{t.PricePerUnit:F4}," +
                         $"{t.NetCost:F2}," +
                         $"{t.TotalTaxAmount:F2}," +
                         $"{t.AnomalyScore:F2}," +
                         $"{t.Confidence:F2}," +
                         $"{t.Status}," +
                         $"{t.ClaimAmount:F2}," +
                         $"{t.ClaimSchedule}," +
                         $"\"{t.ReviewedByUserName}\"," +
                         $"\"{t.ApprovedByUserName}\"," +
                         $"\"{t.AnomalyReason?.Replace("\"", "\"\"")}\"");
        }

        // Log export
        await _auditTrail.LogActionAsync(new AuditLog
        {
            Action = "EXPORT",
            EntityType = "ENGAGEMENT",
            EntityId = engagementId.ToString(),
            EngagementId = engagementId,
            UserId = userId,
            UserName = userName,
            UserRole = "",
            Comments = $"Exported {transactions.Count} {status} transactions"
        });

        return sb.ToString();
    }

    private decimal CalculateExpectedTax(TransactionRecord transaction)
    {
        var stateTaxRates = new Dictionary<string, decimal>
        {
            { "CA", 0.539m },
            { "TX", 0.20m },
            { "NY", 0.444m },
            { "IL", 0.454m },
            { "FL", 0.361m },
            { "PA", 0.577m },
            { "OH", 0.385m }
        };

        var taxRate = stateTaxRates.ContainsKey(transaction.MerchantState ?? "")
            ? stateTaxRates[transaction.MerchantState ?? ""]
            : 0.184m;

        if (transaction.K_SafeHarborPercentage.HasValue && transaction.K_SafeHarborPercentage > 0)
        {
            taxRate = taxRate * (1 - transaction.K_SafeHarborPercentage.Value);
        }

        return transaction.Quantity * taxRate;
    }
}
